# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu37p-fsvh2892-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.cache/wt [current_project]
set_property parent.project_path /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/pio_ep_xpm_sdpram_wrap.sv
read_verilog -library xil_defaultlib {
  /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/pcie_app_uscale.v
  /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/pio.v
  /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/pio_ep.v
  /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/pio_ep_mem_access.v
  /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/pio_intr_ctrl.v
  /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/pio_rx_engine.v
  /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/pio_to_ctrl.v
  /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/pio_tx_engine.v
  /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/xilinx_pcie4_uscale_ep.v
}
read_ip -quiet /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/pcie4c_uscale_plus_0.xci
set_property used_in_implementation false [get_files -all /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/ip_0/synth/pcie4c_uscale_plus_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/ip_0/synth/pcie4c_uscale_plus_0_gt.xdc]
set_property used_in_implementation false [get_files -all /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/pcie4c_uscale_plus_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/synth/pcie4c_uscale_plus_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/synth/pcie4c_uscale_plus_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/source/ip_pcie4_uscale_plus_x1y0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/xilinx_pcie4_uscale_plus_x1y0.xdc
set_property used_in_implementation false [get_files /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/imports/xilinx_pcie4_uscale_plus_x1y0.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top xilinx_pcie4_uscale_ep -part xcvu37p-fsvh2892-3-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef xilinx_pcie4_uscale_ep.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file xilinx_pcie4_uscale_ep_utilization_synth.rpt -pb xilinx_pcie4_uscale_ep_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
