# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/pcie4c_uscale_plus_0.xci
# IP: The module: 'pcie4c_uscale_plus_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/ip_0/pcie4c_uscale_plus_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie4c_uscale_plus_0_gt || ORIG_REF_NAME==pcie4c_uscale_plus_0_gt} -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/ip_0/synth/pcie4c_uscale_plus_0_gt_ooc.xdc

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/ip_0/synth/pcie4c_uscale_plus_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4c_uscale_plus_0_gt || ORIG_REF_NAME==pcie4c_uscale_plus_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/pcie4c_uscale_plus_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4c_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/synth/pcie4c_uscale_plus_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4c_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/synth/pcie4c_uscale_plus_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4c_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/source/ip_pcie4_uscale_plus_x1y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4c_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/pcie4c_uscale_plus_0.xci
# IP: The module: 'pcie4c_uscale_plus_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/ip_0/pcie4c_uscale_plus_0_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pcie4c_uscale_plus_0_gt || ORIG_REF_NAME==pcie4c_uscale_plus_0_gt} -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/ip_0/synth/pcie4c_uscale_plus_0_gt_ooc.xdc

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/ip_0/synth/pcie4c_uscale_plus_0_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pcie4c_uscale_plus_0_gt || ORIG_REF_NAME==pcie4c_uscale_plus_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/pcie4c_uscale_plus_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4c_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/synth/pcie4c_uscale_plus_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4c_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/synth/pcie4c_uscale_plus_0_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4c_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/dlau/tmp/pcie_git/pcie_exdes/pcie4c_uscale_plus_0_ex/pcie4c_uscale_plus_0_ex.srcs/sources_1/ip/pcie4c_uscale_plus_0/source/ip_pcie4_uscale_plus_x1y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pcie4c_uscale_plus_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
